### ISSUE TITLE
ApartApp Hall Preference: Unable to change hall ranking

### ISSUE THREAD

**Issue by glgnkim** [gordon-cs/gordon-360-ui#1039]
When the user tries to change the hall ranking, the whole page refreshes and it no longer lets the user either add or remove halls.
To reproduce this error, add at least two apartments. Then, try changing its ranking. It will refresh the page back to the landing page. If you try to edit the application, it will not let you do it. It may look as if it is doing something, but eventually, it will return an error.

**Comment by NerdyGriffin** [comment]
Wow, I have not been able to reproduce that error yet, but the hall list is also not working a several other ways, so I will have to fix those first (or most likely it's all part of the same root cause)
