### ISSUE TITLE
Make a list of UI changes needed before promoting newtrain to 360 (2)

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#113]
Use marked-up screen shots and drawings where possible, with words as needed to clarify style guide.

**Comment by russtuck** [comment]
[Here's a list](https://docs.google.com/document/d/1OPA4HkV7kI1l47mzM6_J7LNpSpUHoq8w86GQqRZJlic/edit?usp=sharing).

**Comment by russtuck** [comment]
Posted screen shots with annotations on the white board.

**Comment by russtuck** [comment]
The next question is what to do with this list.  Probably some items are included in existing issues, and those should be noted.  The rest should probably be grouped appropriately into new issues.

This is in "needs review" so people can check and correct the list, and agree or disagree with opinions it contains.  After that, I'll take it back and work on getting all the items into appropriate issues (unless someone else would like to do that).

**Comment by softwary** [comment]
[Here is another list.](https://docs.google.com/document/d/1lndc_8oB5lV94IQNt_3C8TL4hLjXn6OAbX5uUR65Cqo/edit?usp=sharing)
