### ISSUE TITLE
Mailboxes & Combinations in 360

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1145]
Jordan Tymann has requested that students be able to see their mailboxes and combinations somewhere on the MyProfile page. This would prevent a lot of the work that the mailroom has to do in managing the combinations and handing them out to the users who need to use them.

I have already put the mailboxes in our SQL Server [synergy] database at [dbo].[Mailroom_Mailboxes], and they will need to be brought into the [CCT] database.

**Comment by josh-peters-2357** [comment]
@bennettforkner , I don't see the location you mentioned that the mailboxes will be at- are they already moved to CCT?
