### ISSUE TITLE
Legend has reappeared on DaysLeft Doughnut

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#1149]
The graph legend was purposefully disabled on the DaysLeft doughnut, but after the most recent release it has reappeared:
<img width="590" alt="Screen Shot 2021-05-29 at 9 53 26 AM" src="https://user-images.githubusercontent.com/35319956/120072849-b8d20900-c063-11eb-919b-a63b10d5e5d8.png">

**Comment by Davideo37** [comment]
I just checked the live version of 360 and the develop branch, I don't see the legend appearing on either of them. Was this already fixed?

**Comment by EjPlatzer** [comment]
It appears that this bug is specific to the `DaysLeft` component shown to non-students (but doesn't affect the `CLWCreditsDaysLeft` component shown to students). IF you log in with 360.stafftest (or 360.facultytest), you should be able to see the legend. It's also likely you have a cached version of the page and so might need to reload it for it to appear (that happened to me).
