### ISSUE TITLE
Separate Leaders/Advisors from Members on Groups page

### ISSUE THREAD

**Issue by Davideo37** [gordon-cs/gordon-360-ui#1181]
This came up while meeting with some club leaders in regards to issue #734. The current group page displays group leaders interspersed with normal group members, organized by alphabetical last name. The leaders requested that the leaders/advisors for a group be separated into their own list, either above or below the standard member list.

Here's a view of what the current system displays for a group member list
![image](https://user-images.githubusercontent.com/70544021/121399528-81494380-c924-11eb-984b-50daad3517db.png)

**Comment by EjPlatzer** [comment]
Would this make the Contact lists redundant? If we separate out group leaders and advisors, then we could have that absorb the only unique feature of the contact list, which is a `mailto:` link.
<img width="571" alt="Screen Shot 2021-06-09 at 1 17 22 PM" src="https://user-images.githubusercontent.com/35319956/121399998-0896b700-c925-11eb-9e87-0fd50774985f.png">

**Comment by Davideo37** [comment]
Merging the two sounds like a good idea. The leaders we talked to acknowledged the contacts list but also wanted to keep the leaders/advisors separate from the other members in the list. Although if we did eliminate the leaders from that section, I am concerned there could be an issue with non-members being unable to view the contact information for the leaders in order to apply for the club.

**Comment by roddy3** [comment]
reference issue `#1200`

**Comment by roddy3** [comment]
Closed by #1200
