### ISSUE TITLE
Add Leaders/Members Picture to Groups page

### ISSUE THREAD

**Issue by Davideo37** [gordon-cs/gordon-360-ui#1182]
Another feature that was posed in our meeting with some of the club leaders while working on issue #734. The leaders wanted the page viewers to be able to see a small profile picture next to the each of the club's leader's/advisor's names so members could better know who their leaders are by face and not just by name.

Add club event calendar  on the group page for the academic year/ which can be updated every year. 
Past history of the club, how it started and how it is going: kind of my about in 360.gordon

Here is what the group list currently shows:
![image](https://user-images.githubusercontent.com/70544021/121400388-878bef80-c925-11eb-9dc4-cd4c6051d5c8.png)

And this is a mockup of what the proposed change could look like:
![mockup](https://user-images.githubusercontent.com/70544021/121401315-92934f80-c926-11eb-9701-dcacd49c0f5f.png)

**Comment by roddy3** [comment]
Pictures of the Leaders/Advisor of the group next to their names, see an example below  



![Screen Shot 2021-06-09 at 1 23 02 PM](https://user-images.githubusercontent.com/60272749/121400744-efdad100-c925-11eb-81c3-03079869a54d.png)



Have a place where they can share their past important events, and also their about/origins pretty much similar to what 360 has see example below



![Screen Shot 2021-06-09 at 1 29 49 PM](https://user-images.githubusercontent.com/60272749/121401608-e43bda00-c926-11eb-8240-d3c174a83dd5.png)

**Comment by roddy3** [comment]
Closed by #1200
