### ISSUE TITLE
PeopleSearch: Make photos larger in results list

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#1197]
The current thumbnail photos in the advanced search results list are useful if you already know the person, but too small to see what anyone really looks like.  Potential solutions include:

* make photos 2-3 times larger
* hover (or tap on mobile) photo to pop up "full size" image (and tap again to dismiss on mobile)

**Comment by EjPlatzer** [comment]
Closed by #1213
