### ISSUE TITLE
Add group Video in Involvement page

### ISSUE THREAD

**Issue by roddy3** [gordon-cs/gordon-360-ui#1205]
Add a second level of image fields in Involvenent, one or two to the Group Page, separate from the main Group Image icon, for groups to post sociable activity images. Can there be an "upload video" field for a mini-commercial for a Group?

**Comment by EjPlatzer** [comment]
After reviewing this with @ChrisImagineer, we decided that 360 is meant to be a daily-use platform for students, not an advertising space for clubs. Clubs can link out to their own website within their involvement profile.
