### ISSUE TITLE
Add check box in people search for larger pictures

### ISSUE THREAD

**Issue by roddy3** [gordon-cs/gordon-360-ui#1212]
Having another check box that people can check it if they want to see a larger picture of people.

**Comment by Davideo37** [comment]
Updated view of UI when box is unchecked vs checked.
![ui](https://user-images.githubusercontent.com/70544021/123447679-1fd1d780-d5a8-11eb-95d6-5b3dc3e24b4b.png)
![ui2](https://user-images.githubusercontent.com/70544021/123447688-22343180-d5a8-11eb-9d2c-89000b8d07c7.png)
