### ISSUE TITLE
Faculty/Staff home address privacy in people search

### ISSUE THREAD

**Issue by jsenning** [gordon-cs/gordon-360-ui#1227]
Faculty/Staff have the option to mark their address as private and 360 honors this.  However, when we search by town we find all people with that town in their address.

This may not be an issue, and perhaps the privacy option should be revoked once we disable people search on go.gordon since we do not show street addresses.

**Comment by bennettforkner** [comment]
At the very least, we should start with hiding facstaff from search results if their address is set to private. You can change this line to also exclude those whose address is private

https://github.com/gordon-cs/gordon-360-api/blob/371359bef6a983ae53fc957eb91c1e10a3f2c69d/Gordon360/Services/AccountService.cs#L171-L173

**Comment by charlielee144r** [comment]
@jsenning We don't see the same issue on 360 at the moment. @bennettforkner set his profile address to be private and he was no longer seen on the people search.

**Comment by bennettforkner** [comment]
LGTM
