### ISSUE TITLE
Disable health pop-up but keep health tab

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#1228]
Disable the health check popup from the home page, but leave the health tab unchanged.  This way, nobody will be required to make a report in order to see the home page, but they can still report if needed.
Details in the thread below

Forwarded Conversation
Subject: Wellness Check on Gordon 360
------------------------

From: Debbi Tuck <Debbi.Tuck@gordon.edu>
Date: Wed, Jun 30, 2021 at 9:44 AM
To: Chris Hansen <Chris.Hansen@gordon.edu>, Michelle Papanicolaou <M.Papanicolaou@gordon.edu>
Cc: Russ Tuck <russtuck@gmail.com>

I don’t know who is the right person to ask this question, but I am wondering who can remove the wellness check from 360 that pops up every time you go into 360?  With the changes to people search, I have been on 360 much more than normal and noticed that at least for staff, it is still a pop-up that you have to fill out to get to the home page. 

Thank you,
Debbi

Debbi Tuck
Special Assistant to the President
HR Training and Project Manager
Gordon College

----------
From: Chris Hansen <Chris.Hansen@gordon.edu>
Date: Wed, Jun 30, 2021 at 11:01 AM
To: Evan Platzer <Evan.Platzer@gordon.edu>, Michelle Papanicolaou <M.Papanicolaou@gordon.edu>, Debbi Tuck <Debbi.Tuck@gordon.edu>
Cc: Russ Tuck <russtuck@gmail.com>

+ Evan Platzer

Debbi, is this officially going away?  For the fall as well?  If so, Evan can help navigate this change. 

Thanks!
Chris

----------
From: Russ Tuck <russtuck@gmail.com>
Date: Wed, Jun 30, 2021 at 11:04 AM
To: Chris Hansen <Chris.Hansen@gordon.edu>
Cc: Evan Platzer <Evan.Platzer@gordon.edu>, Michelle Papanicolaou <M.Papanicolaou@gordon.edu>, Debbi Tuck <Debbi.Tuck@gordon.edu>, COVID-19 <covid-19@gordon.edu>

The 360 team can work with Evan on the change, but we don't set policy.  Now might be a good time to stop the prompt, but retain the tab so people can still report symptoms.  Adding covid-19 to see if someone there can approve this (or say to leave it).

In the meantime, you can also just ignore the health check.  The quick search box and all the other tabs still work.  The only thing it hides is the home page, with dining balance, chapel credits, etc. 

   Russ

----------
From: Debbi Tuck <Debbi.Tuck@gordon.edu>
Date: Wed, Jun 30, 2021 at 11:08 AM
To: Russ Tuck <russtuck@gmail.com>, Chris Hansen <Chris.Hansen@gordon.edu>
Cc: Evan Platzer <Evan.Platzer@gordon.edu>, Michelle Papanicolaou <M.Papanicolaou@gordon.edu>, COVID-19 <COVID-19@gordon.edu>

Thank you all for working on this.

Debbi

----------
From: Chris Jones (Staff) <Chris.Jones@gordon.edu>
Date: Wed, Jun 30, 2021 at 11:27 AM
To: Debbi Tuck <Debbi.Tuck@gordon.edu>, Russ Tuck <russtuck@gmail.com>, Chris Hansen <Chris.Hansen@gordon.edu>
Cc: Evan Platzer <Evan.Platzer@gordon.edu>, Michelle Papanicolaou <M.Papanicolaou@gordon.edu>, COVID-19 <COVID-19@gordon.edu>

I agree with not fully taking it away, but not having it pop up in your face.  We just don’t know what the fall will be like yet, but at least having a way to report symptoms would be good.

Chris

Chris Jones
Vice President for Administration & Emergency Management Coordinator, Gordon College

----------
From: Evan Platzer <Evan.Platzer@gordon.edu>
Date: Wed, Jun 30, 2021 at 11:29 AM
To: Chris Jones (Staff) <Chris.Jones@gordon.edu>, Debbi Tuck <Debbi.Tuck@gordon.edu>, Russ Tuck <russtuck@gmail.com>, Chris Hansen <Chris.Hansen@gordon.edu>
Cc: Michelle Papanicolaou <M.Papanicolaou@gordon.edu>, COVID-19 <COVID-19@gordon.edu>

That sounds like a good plan to me. It’s simple enough to remove it from the homepage but leave the wellness tab operational.

Russ, do the practicum students have bandwidth for this? If not, I can submit a pull request this afternoon.

Thanks,
Evan

----------
From: Russ Tuck <russtuck@gmail.com>
Date: Wed, Jun 30, 2021 at 1:04 PM
To: Evan Platzer <Evan.Platzer@gordon.edu>
Cc: Chris Jones (Staff) <Chris.Jones@gordon.edu>, Debbi Tuck <Debbi.Tuck@gordon.edu>, Chris Hansen <Chris.Hansen@gordon.edu>, Michelle Papanicolaou <M.Papanicolaou@gordon.edu>, COVID-19 <COVID-19@gordon.edu>

Thanks, Chris!  And thank you, Debbi, for asking a great question!

Evan, thanks for your great work helping teach and lead the practicum students, and also for giving the health check a big upgrade between semesters! The practicum team can make this change.  It might not be today, but it should be in the next release, which should be within a week now that we've done one.

   Russ
-------------------

<img width="484" alt="Screen Shot 2021-07-01 at 11 16 18 AM" src="https://user-images.githubusercontent.com/60272749/124148748-f0b2de80-da5d-11eb-9623-af1831671a76.png">
------------------

**Comment by roddy3** [comment]
Closed by #1234
