### ISSUE TITLE
Add banner to Go Site to direct people to 360 people search

### ISSUE THREAD

**Issue by jsenning** [gordon-cs/gordon-360-ui#1285]

**Comment by EjPlatzer** [comment]
This is complete.

When you access People Search on the GO site, you are now presented with this page:
![image](https://user-images.githubusercontent.com/35319956/135876429-ff47a572-84e5-46a5-8e59-3563f8570ccb.png)

Clicking okay sends you to [`https://360.gordon.edu/people`](https://360.gordon.edu/people).

You have to read the fine print and click the bottom link to continue on to regular GO site People Search.
