### ISSUE TITLE
Schedule should show next term

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#1326]
As I write this, fall classes are getting ready to start, and I keep looking for student schedules on their profile pages.  (I could find them other places, but that's harder and slower.)  But 360 is still showing the last summer term schedule, which isn't helpful.  

I think that as soon as a term is over (so after finals end), the schedule should start showing the next term.

**Comment by ChrisImagineer** [comment]
How complicated would it be to have a "select session (term)" option showing current or next? Faculty staff might want to know either a current schedule OR a next schedule (like Russ describes). There's a similar select-session/term feature on the Involvements page

**Comment by bennettforkner** [comment]
I'm not sure the selector would make a lot of sense logically. The idea is that this schedule is supposed to represent the current week. It is not necessarily tied to a specific term as far as the user is concerned. Maybe if it was a date (or week) selector, then yes, it would make sense as far as the purpose of that schedule goes.

**Comment by russtuck** [comment]
The schedule currently only contains courses, so it is entirely term dependent.  (It was once possible to edit it, and user edits, if we make them work, are firmly anchored in "now" and so independent of term.)

**Comment by andrew-wzj** [comment]
we cannot access the specific schedule item due to query being handled by the Stored Procedures

**Comment by andrew-wzj** [comment]
from the method: public async Task<IEnumerable<ScheduleViewModel>> GetScheduleStudentAsync(string username)
we need to write two methods similar to this one, and one method using two argument (username and session code) and not return the current session schedule.

**Comment by mla04762** [comment]
The pull request linked to this query is: #1870, we have also converted the class component files to functional components for schedulepanel and schedulecalendar
