### ISSUE TITLE
Show ID number for everyone

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#1328]
For students, the ID number is show in the "personal info" box in "my profile".  This would be just as useful for facstaff.  Let's rename it "Gordon ID" and show it to everyone.  (Or leave it as "Student ID" for students, and call it "Gordon ID" for everyone else.)

I say "everyone else" to include any alumni who are able to login.

**Comment by Kindlewing** [comment]
Is this where the ```studentID``` is defined in ``` src/components/Profile/components/PersonalInfoList ```, or somewhere else (Starting on line 367)?

```reactjs
const studentID =
    isStudent && myProf ? (
      <ProfileInfoListItem
        title="Student ID:"
        contentText={ID}
        ContentIcon={
          <Grid container justifyContent="center">
            <Grid container direction="column" justifyContent="center" alignItems="center">
              <LockIcon />
              Private
            </Grid>
          </Grid>
        }
        privateInfo
        myProf={myProf}
      />
    ) : null;
````

**Comment by Kindlewing** [comment]
Removed my last comment: I figured it out.
