### ISSUE TITLE
Search does not work on mobile (2)

### ISSUE THREAD

**Issue by softwary** [gordon-cs/gordon-360-ui#133]
It doesn't work on iPhones

My iPhone 7 can't search on FireFox, Chrome, or Safari browsers

**Comment by scmac97** [comment]
Works on Android, though &mdash; pretty strange.

**Comment by TheGreatMaximus** [comment]
This appears to be a problem with the onChange event not firing on mobile devices because key and tap events are considered to be different from computer key and click events.
