### ISSUE TITLE
Confetti or flying geese?! - Adding a visual reward for completing an action. Is this possible?

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#1331]
Any chance of making the UI more engaging - like a pop of confetti or a flying goose when a user completes an action - like submitting the daily Wellness Check? or Joining a Club?  Those surprise quick animations can be rewarding and brighten someone's day.

**Comment by bennettforkner** [comment]
One option if we decide to do this:
https://daniel-lundin.github.io/react-dom-confetti/
