### ISSUE TITLE
Add an FAQ section for clubs

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#1336]
Add an FAQ section where clubs can write and answer frequently asked questions by students

**Comment by EjPlatzer** [comment]
Per discussion between myself and @ChrisImagineer, 360 is meant to allow for finding and joining involvements, not as fully-featured CMS for clubs. The verdict was that involvements admins can use the involvement description (which has a limit around 2 billion characters) for most purposes. Anything more sophisticated probably belongs outside 360, e.g. on their own website.
