### ISSUE TITLE
Retain Campus employment on Experience Transcript when HR shift takes place.

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#1337]
Keeping the list of Campus employments for users on their Experience Transcript when the HR shift happens this winter

**Comment by bennettforkner** [comment]
The HR system has already changed over and all of the data is in the same format as before as far as 360 is concerned. The only thing that is changing this winter should be the payroll system and timesheets. Nothing should change with 360 except the deprecation and removal of the student timesheets system.

**Comment by EjPlatzer** [comment]
As @bennettforkner mentioned, the HR data shift is complete, and student employment info has not been affected. There is a separate issue covering Experience Transcript errors not related to the HR switch over, so I'm closing this one.
