### ISSUE TITLE
Calendar view of events

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#1361]
Calendar view of events; how much does this overlap with 25Live?

**Comment by ChrisImagineer** [comment]
Recommend only a Day or Week option. I think the month would be highlight visually complex to fit for mobile screens. But a Day view with a scroll for the next days. Or maybe a week, but even then that might be visually hard to fit on mobile screens.

**Comment by EjPlatzer** [comment]
This should be kept consistent with the Schedule feature on Profile, so that we don't depend on two different calendar packages. This might be blocked by #879 until we decide on what calendar package to use.

**Comment by andrew-wzj** [comment]
I think we could close this since #879 has been addressed
