### ISSUE TITLE
Add Space Between Address Line 1 and Town on Profile

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1362]
There should be a space between the comma and the town/city in a student's address when it is marked as private. See photo.

Test with 360.stafftest or 360.facultytest

![temp](https://user-images.githubusercontent.com/43764277/135888660-c570575f-a8a5-4988-aec2-4542521747ca.jpg)

**Comment by AayushSaini101** [comment]
Please assign this issue

**Comment by bennettforkner** [comment]
Hi @AayushSaini101 , This issue will be assigned to someone on our development team when they are available to work on it. Thanks for your interest in the project!
