### ISSUE TITLE
Fix remaining People Search discrepancies.

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#1363]
Now that we have begun the deprecation of GO People Search, we will be receiving notes about things that 360 is still lacking.

The following have been reported so far:
- Missing minors in minor search: the `Special Education`, `English as a Second Language`, and `TESOL` Minors are not present in the minors dropdown to search by.

**Comment by Kevin-Chu58** [comment]
@EjPlatzer I just checked the current People Search, and found all these missing minors were added to the dropdown.

**Comment by EjPlatzer** [comment]
> @EjPlatzer I just checked the current People Search, and found all these missing minors were added to the dropdown.

Right, I fixed this issue with a database change a while back, but forgot to close this. Thanks for fighting that out!
