### ISSUE TITLE
User Profile Settings Page

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1415]
The MyProfile page is starting to get more and more cluttered as we add controls and settings to it. We continue to come up with new ideas for settings and for new information shown, but do not have a solid place to put all of the controls.

The discussed idea for a solution is combining all of the controls into some sort of "profile options" page, where a user would go to toggle data privacy, change their address with the registrar, change their name, etc. Would love @ChrisImagineer 's thoughts on the value of this and how it could be presented.

**Comment by Kevin-Chu58** [comment]
Should we add a button to Profile that shows the "profile options" dialog, or we add a new "profile options" page into the profile list after clicked our profile image?

**Comment by bennettforkner** [comment]
I think it's fine to keep it as an "edit profile" page for now. Perhaps if we needed a separate settings page in the future, it would be best to have that as its own view. That is the practice of a lot of sites, to have the profile/account settings as their own page separate from site & viewer settings.

**Comment by Kevin-Chu58** [comment]
For this user-experience project, I will just finish the MVP, that is, have only one toggle working properly that alters the public/private state of one info from profile. Then, I will leave this as a draft for future discussion.

**Comment by bennettforkner** [comment]
Quoting from #1399:
>Users should be able to control how their names appear on the 360 profile page. We have had at least one issue where a user has not wanted a former name to show up in parentheses on the page. This inspires the idea that users should be able to control how their name appears on their identification card.

>They should probably be able to select specific parts of their name to show up such as [prefix,first,nickname,middle,last,maiden,suffix] and the parts they select will show up in correct order on their identification card.
This should be handled as a part of the user profile settings page goals.

**Comment by russtuck** [comment]
My Profile page now has nice "edit in place" functionality.
