### ISSUE TITLE
Check-In Home Screen Logic

### ISSUE THREAD

**Issue by dansavlon** [gordon-cs/gordon-360-ui#1435]
Recapping offline discussion. @EjPlatzer, please clarify if I'm misunderstanding, or something below is not possible.

Here is the ideal for how 360 pages should respond during the time of Academic Check-In:

If a user who needs Academic Check-In goes to any 360 page, they will get redirected to the Academic Check-In page until they have completed the Academic Check-In.

After Academic Check-In has been successfully completed (or if Academic Check-In is not required), user attempting to go to any 360 page will get the Wellness Check-In page until they have completed the Wellness Check-In.

**Comment by EjPlatzer** [comment]
I can see about the making Enrollment Check-in mandatory for any page. However, that is not the case for the wellness check-in. It shouldn't prevent the user from using the site. It only displays on the Home and Wellness pages.
