### ISSUE TITLE
add youcanbook.me integration

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#1507]
simple way to find youcanbook.me for those who use it

**Comment by russtuck** [comment]
While this lets me add my link (russtuck.youcanbook.me), and it shows it to me on my own profile page, my public profile does not show a calendar link.

I don't know if this is a general problem, or specific to me.  (On my.gordon.edu, I have both faculty and student tabs, which most faculty don't, simply because I once audited a class and thereby became a student.)  It might be that it's not displaying my link because I'm a student, while actually it should be displaying my link because I'm faculty.

**Comment by bennettforkner** [comment]
Interesting! We can look into the authorization for this and figure out where the issue is. Have you tested someone else such as @jsenning adding a custom link?
