### ISSUE TITLE
Add Primary Academic Advisor w major

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#1509]
? Do student's advisor(s) appear on their Profile? Are those also visible for FacStaff viewers, alongside their major/minor?

**Comment by EjPlatzer** [comment]
Yes, students see their advisors on their profile. It is not currently visible to FacStaff viewers though. Should advisors be visible to all FacStaff, or just a subset?

**Comment by ChrisImagineer** [comment]
I believe its FERPA okay for faculty and staff to see an academic advisor’s name in a student’s profile. It gives a Gordon contact about a student they might encounter. Somewhere on the UI projects board might be a note about adding RD name to the housing profile, too, for that same reason. Would this be a good project for a GoCo developer? Will we be able to do that again this year?

On 09/14/22, 08:25, "Evan Platzer" ***@***.******@***.***>> wrote:


Yes, students see their advisors on their profile. It is not currently visible to FacStaff viewers though. Should advisors be visible to all FacStaff, or just a subset?

**Comment by bennettforkner** [comment]
This update will likely be adding a new row to the PersonalInfoList under the Profile component. See `src/components/Profile/components/PersonalInfoList/index.jsx`
