### ISSUE TITLE
Dining Balance Days Donut filled

### ISSUE THREAD

**Issue by amos-cha** [gordon-cs/gordon-360-ui#1515]
<img width="1238" alt="Screen Shot 2022-09-21 at 5 32 33 PM" src="https://user-images.githubusercontent.com/78386128/191615979-0b2b874f-caa8-4dd4-a99a-3ade2421ea65.png">
I looked at the logic within views/Home/components/CLWCreditsDaysLeft vs DiningBalance and they seem to use different logic despite doing the same thing. 

Currently, CLWCreditsDaysLeft has a functioning donut while DiningBalance doesn't as shown in the image.

**Comment by EjPlatzer** [comment]
You're talking just about the Days Left portion of the graph, right?

**Comment by amos-cha** [comment]
Yep @EjPlatzer

**Comment by EjPlatzer** [comment]
Fixed by #1524
