### ISSUE TITLE
Students are brought to broken page for alumni in involvement

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1553]
If a student views an involvement that has Alumni in it, for example: an involvement from a former semester, and clicks on the name of an alumni, it takes them to the Alumni's profile. The API, rightly so, refuses the request from the student as they are not authorized to view alumni, and the UI page is left loading forever.

There are multiple ways to fix an issue like that, my recommendation would be to un-link alumni names in the involvement if the user is an alumni. Alternatively, we could show a more helpful message to the student user on the Alumni profile page. Or perhaps we could do both!

**Comment by bennettforkner** [comment]
@Kevin-Chu58, did you want to take a look at this after your current PR since you were the one that found it?

**Comment by Kevin-Chu58** [comment]
Sure! I can work on this.

**Comment by Kevin-Chu58** [comment]
Interestingly, when I tried to access an alumni public profile using my student account, it redirected me to Page 404NotFound, but the product didn't do this. Is this because some updates we already made in train but haven't pushed to the product it?
