### ISSUE TITLE
Remove Race & Ethnicity section from the Enrollment Check-in process.

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#1562]
The registrar has requested that we remove all sections relating to Race & Ethnicity from the Enrollment Check-in process on 360.

Per @dansavlon:
>We need to remove the pages related to Race and Ethnicity on the Enrollment Check-In and test thoroughly to make sure that the process completes successfully without them.
>
>Students are changing their race/ethnicity over time, causing anomalies in the regulatory reporting. So we need to shut that down.
>
>Check-in goes live around January 3, so if we could have development and testing done before Christmas break, that would be awesome.

**Comment by bennettforkner** [comment]
Correct me if I'm wrong, but this should be closed @EjPlatzer ?
