### ISSUE TITLE
About Page Versioning is Broken

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1567]
The about page has version info and build time at the bottom, but the logic to insert that is currently broken. I believe it is part of the CD in PowerShell but I don't know for certain.
![image](https://user-images.githubusercontent.com/43764277/201706414-c2afbfdc-db74-4963-a1bb-88cda637b1b5.png)

**Comment by amos-cha** [comment]
API: https://github.com/gordon-cs/gordon-360-api/pull/932

**Comment by EjPlatzer** [comment]
This has been resolved.
