### ISSUE TITLE
People search results links are broken

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#1607]

**Comment by russtuck** [comment]
In the people tab (advanced) search results list, clicking on a person's name goes to a link of the form:
https://360.gordon.edu/people/profile/FIRST.LAST
but this link doesn't exist.  Actual profile links look like this:
https://360.gordon.edu/profile/FIRST.LAST

This appears to be true for all people in advanced people search results.  (Instant people search works correctly.)

**Comment by bennettforkner** [comment]
Thanks for pointing this out Russ! I will get on it right away.

**Comment by bennettforkner** [comment]
I have confirmed that the issue is resolved in production @russtuck .
