### ISSUE TITLE
Add Member Form Does Not Clear Out Previous Details

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1625]
The add member form on an involvement profile is not clearing out old information after I add a member.

I.e. If I add `student.test` as an `advisor` to `Rowing Club` with the Title/Comment `Team Lead`, save, then open the form again to add `staff.test`, the form is still set to `advisor` and `Team Lead`. Instead, the form state should clear itself out when submitted or closed.

**Comment by bennettforkner** [comment]
This can be addressed by updating the `handleAddMember` function in the following file to clear out the `username`, `participationCode`, and `titleComment` state variables when the member has been successfully added.

https://github.com/gordon-cs/gordon-360-ui/blob/a2d7c3bf58d3f13d960c3365dc7fc86f89302154/src/views/InvolvementProfile/components/Membership/components/AdminCard/index.jsx#L55-L88

**Comment by charlielee144r** [comment]
https://github.com/gordon-cs/gordon-360-ui/pull/1687

For some reason, the PR isn't connecting automatically although I referenced it.

**Comment by bennettforkner** [comment]
See my comment on #1687
