### ISSUE TITLE
Involvement Profile: link to member profiles broken on small screens

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#1638]
On the Involvement Profile page, the link to users' profiles is broken on small screens.

The issue is in `/src/views/InvolvementProfile/components/Membership/components/MemberList/components/MemberListItem/index.jsx`. It appears that the large screen view links to `/profile/${member.Username}`, whereas the small screen view links to `/profile/${member.AD_Username}`. 

When we refactored Memberships, I think the member item was changed and the `AD_Username` property is now `Username`, but the links weren't changed everywhere.

**Comment by Khalil-Ullah-Hafeez** [comment]
I would like to work on this issue. Can you assign it to me?
