### ISSUE TITLE
Personal Information Privacy Toggle Broken

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1653]
The Public/Private toggle on the Personal Information card on `MyProfile` is not displaying correctly. When I set my PI to private and then reload the page, the toggle is still set to Public even though the change worked.

![Image](https://user-images.githubusercontent.com/43764277/215543326-5d516fbf-6f02-44cf-b9d8-5425c0eb97e2.png)

**Comment by bennettforkner** [comment]
The issue is likely with something here:

https://github.com/gordon-cs/gordon-360-ui/blob/a2d7c3bf58d3f13d960c3365dc7fc86f89302154/src/components/Profile/components/PersonalInfoList/index.jsx#L486-L498

**Comment by jalajk24** [comment]
@bennettforkner Can I works on this issue ? I am new to open source contribution

**Comment by bennettforkner** [comment]
@jalajk24 we welcome you to open a pull request and propose code changes if you so desire. Unfortunately this application can only be run with our local database, so you will have a hard time testing.
