### ISSUE TITLE
"Congratulations" message still pops up daily

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#1683]
As a faculty member, I don't do the "checkin" at the start of each semester.  But this semester (spring 2023) I got a "congratulations" message about finishing it.  In fact, I still get it the first time I use 360 every day, even though we're weeks into the semester.  By now, I think instead of it being a slight misfeature, it's a bug that developers aren't aware of.  I haven't asked other faculty or staff if they get it.

**Comment by bennettforkner** [comment]
Hi @russtuck Evan and I thought we had a fox for this that we released on Friday 2/18/23. Have you seen this message today still?

**Comment by russtuck** [comment]
I saw it this morning.

**Comment by ArabellaJi** [comment]
I was also seeing the "Congratulations" message previously during the semester but not seeing it recently. Is this issue fixed?

**Comment by russtuck** [comment]
Fixed. I haven't seen this in a long time.
