### ISSUE TITLE
Allow RecIM Admins to Confirm that a Participant has signed the waiver

### ISSUE THREAD

**Issue by bennettforkner** [gordon-cs/gordon-360-ui#1708]

**Comment by bennettforkner** [comment]
@mla04762 what is this closed by? It's best to make a quick note whenever you are closing an issue so that people know why it is no longer relevant or how it has been solved. If there is a Pull Request that goes along with a solution, it's helpful if you link it too.

**Comment by amos-cha** [comment]
@bennettforkner sorry, I accidentally closed it on his computer and was going to link on this end. 
https://github.com/gordon-cs/gordon-360-ui/pull/1810
