### ISSUE TITLE
Cleanup remaining uses of deprecated @mui/styles package

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#1790]
When we upgraded to MUIv5, we added the `@mui/styles` package which allowed us to keep using the old, MUIv4 styling API so that we didn't have to change the styling of many components. However, that package was intended as a transitional tool, and is not being maintained in the long term.

Please find all references to the `@mui/styles` package and update each component to use the same styling solution as the rest of the project.

Below are all the references in every index.jsx file:
- [x] src/components/GordonTooltip/index.jsx
- [x] src/components/Header/components/NavAvatarRightCorner/index.jsx
- [x] src/components/SchedulePanel/index.jsx
- [x] src/components/PWAInstructions/index.jsx
- [x] src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsRecieved/index.jsx
- [x] src/views/Timesheets/index.jsx
- [x] src/views/Timesheets/components/ShiftItem/index.jsx

**Comment by Centerville1** [comment]
Looked through the code for references, no fixes yet.

Below are all the references I found:
- src/components/GordonTooltip/index.jsx
- src/components/Header/components/NavAvatarRightCorner/index.jsx
- src/components/SchedulePanel/index.jsx
- src/compontnet/PWAInstructions/index.jsx
- src/views/InvolvementProfile/components/Membership/components/AdminCard/components/RequestsRecieved/index.jsx
- src/views/Timesheets/index.jsx
- src/views/Timesheetscomponents/ShiftItem/index.jsx

**Comment by bennettforkner** [comment]
@Centerville1, I added your references to the original description above with checkboxes so that we can track which have been fixed.

**Comment by andrew-wzj** [comment]
We mainly completed on cleaning up deprecated `@mui/styles`,but we couldn't really test `RequestsRecieved/index.jsx` is working.
