### ISSUE TITLE
Schedule-Push classes to Google/Apple/Outlook calendars

### ISSUE THREAD

**Issue by andrew-wzj** [gordon-cs/gordon-360-ui#1827]
In Profile Page, make an add to Google/Apple/Outlook calendar button for displaying daily schedule of student and fac.
The schedule section displays user's schedule of current academic semester.
Should the schedule section could also add schedule for following semesters, and review the past semesters' schedule?

**Comment by andrew-wzj** [comment]
For Schedule Panel, there are some related issues before adding the calendar button for schedule.
1. Edit Description button doesn't really do anything 
2. Error while removing the event
3. User can create the event by clicking the schedule panel but it will crash if the value is invalid or undefined (out of 24hours or leave one fill tab blank)
4. Warning messages doesn't pop out
5. More bugs or broken features need to be found....

**Comment by andrew-wzj** [comment]
6. For event which already created and displaying on the schedule calendar, the schedule panel will crash when we try to reset the time of event

**Comment by bennettforkner** [comment]
The schedule component needs a huge refactor or a rebuild from scratch before we add features to it. It is very broken and basically unusable for most people as you mention.

**Comment by andrew-wzj** [comment]
Before we're able to work on pushing classes to calendars, we need to resolve issue #666 . The schedule panel should display course schedule having start date and end date, reminder of holidays (no class).

**Comment by andrew-wzj** [comment]
Now the schedule panel has the header which the branch will be merged today, term selector (fixed api code and displayed selected term course schedule correctly). Now the issue for push classes to calendars is that the button can only push one recurrent course once or push multiple events which are not recurrent (from 'add-to-calendar-button' package  https://add-to-calendar-button.com/examples). 
We could make button to push course schedule (not recurrent), so user only need to edit the recurrence of these events.

**Comment by andrew-wzj** [comment]
The expected functions of add-to-calender button
(if student and faculty have ASY course during the semester, ASY will display as reminder or whole day event) 
- [ ] User click specific item and pop over its details and button
- [ ] The add-to-calender button (set the recurrence of event and same format for same course)
- [ ] test its validation
