### ISSUE TITLE
Replacing the default seal with the new logo for involvements

### ISSUE THREAD

**Issue by ahwnsals1234** [gordon-cs/gordon-360-ui#1829]
Because the default picture for the involvements are set to the previous Gordon seal, it would be preferred to update the default to the new Gordon logo.

**Comment by bennettforkner** [comment]
I would consult with design before doing anything with this one. It is not a "new logo", it is a marketing logo. It has repeatedly been referenced as something to be used specifically for marketing and admissions, not internal, official use.

**Comment by ahwnsals1234** [comment]
Thank you for the feedback, we emailed design to set a meeting soon. In the mean time, there might be ideas, but there would not be any big changes made.
