### ISSUE TITLE
Timesheets Approval (move from Go to 360)

### ISSUE THREAD

**Issue by ArabellaJi** [gordon-cs/gordon-360-ui#1835]
UI
- [ ] bring the admins to /timesheets/admin instead of /timessheets when they press Timesheets Tab
    - [ ] a new page with route /timesheet/admin only accessible for admits
- [ ] timesheet cards for the admins to view the submitted items (Gordon ID, Name, Job, Hourly Rate, Regular Hours, Overtime Hours, Total Gross Earnings, ...)
    - [ ] button to order by Name or Job?
- [ ] approve button and deny button for each timesheet card
    - [ ] approve button is only active for unapproved items, deny button is active for all items
    - [ ] a confirmation message when pressed approve or deny button?
    - [ ] button to include approved items or not? (default may be not seeing the approved items, but admins can choose to see them)
    - [ ] button to approve all?
- [ ] show the items from not only the current semester but also the previous semesters if we have those data in database so that 

API
- [ ] GET: get the unapproved timesheet item
- [ ] PUT: update the approved or unapproved status of the item

**Comment by bennettforkner** [comment]
How can I "♥" an issue?

Thanks for looking into this @ArabellaJi ! It's a great feature to get moved over.

**Comment by ArabellaJi** [comment]
Thanks!! :smirk:

**Comment by ArabellaJi** [comment]
According to what Bennett and I discussed on another platform, all student timesheets are going to be moved to Criterion in the Fall 2023. Therefore, this issue is on hold.

**Comment by russtuck** [comment]
Student timesheets were moved to criterion, so this is no longer relevant.
