### ISSUE TITLE
Schedule Panel: Remove Event

### ISSUE THREAD

**Issue by andrew-wzj** [gordon-cs/gordon-360-ui#1840]
Remove button is supposed used for deleting events except course schedule (the change of student's course schedule should only valid for registration).
Fix the error message which popped out when we use the Remove Event.
Dr. Tuck mentioned the new feature could be made on removing event by dragging the event to Remove Event Button.

**Comment by bennettforkner** [comment]
@andrew-wzj could you please add a description to this issue?
