### ISSUE TITLE
Updating favicon for Gordon 360

### ISSUE THREAD

**Issue by ahwnsals1234** [gordon-cs/gordon-360-ui#1841]
The favicon for Gordon 360 is the previous Gordon logo. Following the update in our gordon.edu website, it would be a great idea to update the favicon for Gordon 360 as well.

**Comment by bennettforkner** [comment]
I would consult with design before doing anything with this one. It is not a "new logo", it is a marketing logo. It has repeatedly been referenced as something to be used specifically for marketing and admissions, not internal, official use.

**Comment by ahwnsals1234** [comment]
Thank you for the feedback, we emailed design to set a meeting soon. In the mean time, there might be ideas, but there would not be any big changes made.

**Comment by ahwnsals1234** [comment]
#1956
