### ISSUE TITLE
Retain results in People Search

### ISSUE THREAD

**Issue by ArabellaJi** [gordon-cs/gordon-360-ui#1851]
When people search for someone on the People page, there will be a number of results listed (Image 1). Then, if they select one of them, they will go to the Profile page (Image 2). However, if they press the back arrow to go back to the original People page, the text they entered is still there (in this case, 360 is still in the "First Name" field), but the results are gone (Image 3). It would be nice if the results were retained when people came back.

![Image](https://github.com/gordon-cs/gordon-360-ui/assets/78650688/9f33fb2c-158f-4ef2-93fa-9fd723c3f0ec)
![Image](https://github.com/gordon-cs/gordon-360-ui/assets/78650688/5c3070d1-aff8-4a3b-b0b7-c8ec797a12c5)
![Image](https://github.com/gordon-cs/gordon-360-ui/assets/78650688/f7c6a1d3-9a7a-4a6d-bc63-0b0e34f34e98)

**Comment by antoniavonto** [comment]
https://github.com/gordon-cs/gordon-360-ui/pull/1990

**Comment by antoniavonto** [comment]
this issue was solved, but there is still space for efficiency improvement
