### ISSUE TITLE
Add Header to Event page

### ISSUE THREAD

**Issue by jhammond4** [gordon-cs/gordon-360-ui#1853]
Adding a header to the top search tab in events for consistency. This means the Attended CL&W button needs to be moved-for the time being, I moved it down by the other buttons but the formatting needs improving. I tried shortening the search bar and having its length change with the screen size, but I couldn't get the function to work. As is, I set the search bar length to its shortest length based on screen size that keeps the other buttons in a line. I'm open to other suggestions on what to do with it

**Comment by jhammond4** [comment]
I got the Search Bar Length function to work, so disregard that part now

**Comment by Luke-W-Hart** [comment]
Closing as this is done. Nice work!
