### ISSUE TITLE
Improvements to Involvements page UI

### ISSUE THREAD

**Issue by jhammond4** [gordon-cs/gordon-360-ui#1860]
Potentially add headers to each tab in Involvements for consistency-there is an older issue (https://github.com/gordon-cs/gordon-360-ui/issues/1471) that looked into creating a tabbed UI, but I'm not sure how close to completion it is. That may look better, but headers can also easily be added if necessary.

**Comment by EjPlatzer** [comment]
I would just like to mention that there is an open pull request (#1735) for the tabs view and the work is mostly done, there's just some code clean up and a couple of subtle design decisions to be made, so I would rather see effort focused on that.

**Comment by russtuck** [comment]
Addressed in other issues.
