### ISSUE TITLE
CSS Overhaul Project

### ISSUE THREAD

**Issue by Centerville1** [gordon-cs/gordon-360-ui#1863]
After meeting with Evan, and doing some experimenting, we're wanting to update all the CSS to use theme variables defined in the theme.ts file.

This is a very big code quality change, involving adding a color palette to support having different themes in the future.  We are also converting a lot of in-line styles to use separate CSS in many places.

- [x] Research how to approach this project, "what we need to do"
- [x] Organize our approach (We are each working on a component at a time in parallel, and then merging into one branch) "How to do it"
- [x] Work on refactoring the styling throughout the code "do the thing"
- [x] Write documentation for the project description, decision making, and planning
- [x] Write maintenance documentation for how to do styling going forward, to increase consistency in styling going forward (Partially done, might add some more for dark mode).

Prototype Dark Mode using our changes:
![Image](https://github.com/gordon-cs/gordon-360-ui/assets/115327391/06b1cba7-4783-4c3d-9af3-d0028b3f9011)

![Image](https://github.com/gordon-cs/gordon-360-ui/assets/115327391/e0f4329d-412c-4f6c-8081-a9cc63446306)

With the changes we've made, it's super easy to modify the color palette, and create an alternate color mode.  I changed the whole site from solid orange test colors to this dark mode in about 10 minutes.  It's not perfect, but it's close with very little effort.

#### Related Issues
#1876  - Foundation and Research/initial PR
#1877 - Majority of the actual work

**Comment by Luke-W-Hart** [comment]
Seems like this is done @Centerville1 ?
Hope space is treating you well! 🙂

**Comment by Centerville1** [comment]
> Seems like this is done @Centerville1 ?
> Hope space is treating you well! 🙂 

Yeah, I think we probably "did the thing" 😂...  I'll close it 🫡
