### ISSUE TITLE
Branding Update

### ISSUE THREAD

**Issue by Centerville1** [gordon-cs/gordon-360-ui#1878]
Progress and tracking on updating logos, images, colors, etc. to the new brand standards.

- [x] Complete style and theming overhaul
- [x] Create a palette for light mode color theming
- [x] Create a palette for dark mode color theming
- [x] Update logo on header
- [ ] Update default profile images (src/components/Header/components/NavAvatarRightCorner)
- [x] Update default involvements image

#### Related Issues:

#1841 
#1828 
#1829

**Comment by Luke-W-Hart** [comment]
@Centerville1 The first on the checklist is done I think (right?). For 5 (Update default profile images), do you mean changing this


![Image](https://github.com/gordon-cs/gordon-360-ui/assets/123050501/a00fa818-80ca-4406-8171-5c3366ab999c)

to the new logo, just like it is for the default involvements image except without the "Gordon College"?


![Image](https://github.com/gordon-cs/gordon-360-ui/assets/123050501/6adc49f9-f47b-4af8-9c95-da7d92de9bd5)
