### ISSUE TITLE
Users Cannot Delete Social Media Link Easily

### ISSUE THREAD

**Issue by ArabellaJi** [gordon-cs/gordon-360-ui#1879]
From what I observed, the social media links can be deleted, but it works very wield (definitely a bug). If people edit their social media links, submit, and directly edit them again, then the text field can still remember their social media links, and they can remove them and submit again, then the social media links are deleted. However, if people edit their social media link and go to another page, then when they come back, the text field cannot remember what they typed, so to remove their social media links, they need to do what I described previously.
Thus, I think this is a UI problem instead of an API one. I will add a UI issue related to this.

_Originally posted by @ArabellaJi in https://github.com/gordon-cs/gordon-360-api/issues/865#issuecomment-1595186385_

**Comment by ArabellaJi** [comment]
This feature works fine on Dr. Senning's profile, so maybe this bug only appears on student's side?

**Comment by jaeminlee0515** [comment]
I tried to re-enact what you mentioned above but I wasn't able to see the problem that you were seeing. On the other hand, I actually found that there was a problem with saving a social media link (you can save it but when you navigate to a different page or refresh the page, the social media link disappears).

**Comment by andrew-wzj** [comment]
I haven't observed these bus from my view so far (from 360train)

**Comment by Luke-W-Hart** [comment]
Fixed by https://github.com/gordon-cs/gordon-360-ui/pull/2229
