### ISSUE TITLE
Blue headers of Saved Shifts and Submitted Shifts in Timesheets are uneven

### ISSUE THREAD

**Issue by ahwnsals1234** [gordon-cs/gordon-360-ui#1898]
The blue headers of Saved Shifts and Submitted Shifts in Timesheets are uneven. The left of the header reaches the end of the box and the right of the header does not.

![Image](https://github.com/gordon-cs/gordon-360-ui/assets/78441590/e4d1aebe-e14e-49bb-afb1-f45b2e3b4f68)

**Comment by Luke-W-Hart** [comment]
Closing as timesheets got moved to Criterion. :)
