### ISSUE TITLE
Better option for selecting range of years in people search

### ISSUE THREAD

**Issue by antoniavonto** [gordon-cs/gordon-360-ui#1900]
I like the idea of a slider here, but I'm concerned it may be the wrong choice in terms of UX. Since the range is several hundred years, it takes a lot of effort to get the value exactly what you want it to be. Consider someone on a touch screen who has slightly shaky hands - they would probably have great difficult setting this to be exactly 1970-1974, for example. I think in the interest of UX, we might need to change this to two separate year inputs.

_Originally posted by @EjPlatzer in https://github.com/gordon-cs/gordon-360-ui/pull/1844#discussion_r1237546980_

**Comment by dli505** [comment]
https://github.com/gordon-cs/gordon-360-ui/pull/2240
