### ISSUE TITLE
people search department drop down order

### ISSUE THREAD

**Issue by andrew-wzj** [gordon-cs/gordon-360-ui#1927]
The "department" drop down menu for employees in people search has an odd order, because a seemingly random set of departments are listed as "Office of ...", "Center for", or "Department of".  It might be easier to find things if a these prefixes were shown on the end, like "Athletics, Office of".  

This could be done with regular expressions in the UI, or the API.  It could also be done in the database, but that might have undesirable consequences like changing how the department name appears in other places.  Once an approach is determined, we can convert this to an issue in the appropriate repo.

**Comment by antoniavonto** [comment]
https://github.com/gordon-cs/gordon-360-ui/pull/1944
