### ISSUE TITLE
student/alumi search options apply even when student and alumni aren't checked

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#1929]
To reproduce:
In people search, select a major, then unselect the student box.  Now the major is grayed out (so it can't be changed), but it's still in the URL and impacting the search results, so there can't be any results.  

When fields are grayed out, it would make sense to not use them in the search (or URL).  Taking them out of the URL would probably have the effect of clearing them, which could be good or bad.

It might be argued that this isn't a bug, or that the alternatives are worse.  But I think it deserves some consideration and a decision.

**Comment by antoniavonto** [comment]
This issue was solved, but there is still space for improvement in efficiency
