### ISSUE TITLE
Schedule: Missing Saturday course

### ISSUE THREAD

**Issue by andrew-wzj** [gordon-cs/gordon-360-ui#1930]
There are a few Saturday courses in course catalog, but the schedule panel doesn't display it. 
The issue is no corresponding SATURDAY_CDE for displaying Saturday class in `schedule.ts` and api.
Maybe need to change the database structure for adding SATURDAY_CDE or ignore this case.

**Comment by mla04762** [comment]
We realized that this feature isn't necessary because the only saturday courses that exist are one day events. And because we are moving towards a more repetitive schedule type of panel, we don't need to add one-time occurring events.
