### ISSUE TITLE
Overhaul Header and Site Navigation

### ISSUE THREAD

**Issue by Centerville1** [gordon-cs/gordon-360-ui#1932]
Because there are many new tools and pages for 360 that aren't easily navigable currently, and because there is such limited space in the header, we want to work towards an updated navigation solution.

This is based on previous thought from #1035, but we decided that adding an extra navigation menu is unnecessary.

The idea at this point is to use the hamburger menu from mobile at all times for most navigation, use a new Gordon 360 logo as a home button, and potentially allow users to pick 3-5 apps to put on their header.

Related PR: 
#1933

**Comment by russtuck** [comment]
Mostly done.  Don't yet allow users to pick favorite tabs.  We'll make that a separate feature.
