### ISSUE TITLE
User Cannot Save Social Media Link (Only temporarily)

### ISSUE THREAD

**Issue by jaeminlee0515** [gordon-cs/gordon-360-ui#1957]
Found this while looking at [#1879](https://github.com/gordon-cs/gordon-360-ui/issues/1879), where if you put in a valid social media link and click "Submit", it will show that it is saved and added to your profile page. But when you refresh the page or go to a different page and then navigate to the "My Profile" page, the social media link is gone.

**Comment by Luke-W-Hart** [comment]
FIxed by #2229
