### ISSUE TITLE
Days Left Component: Days Remaining is the wrong color

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#1979]
The Days Remaining section of the Days in the Semester graph is Gordon Blue, which is the same color as the Days Complete section:
<img width="254" alt="image" src="https://github.com/gordon-cs/gordon-360-ui/assets/35319956/f97015da-4084-4084-8968-68a4bb67caa5">
Days Remaining is supposed to be a different color (previously light gray I believe) to visually differentiate it.

**Comment by andrew-wzj** [comment]
Is it still a issue or already been fixed?

**Comment by Luke-W-Hart** [comment]
This has been fixed.
