### ISSUE TITLE
Schedule: Term selector should only displays term with course

### ISSUE THREAD

**Issue by andrew-wzj** [gordon-cs/gordon-360-ui#2017]
Term selector now displays all term selection for every user. To improve user experience, we should make user only allowed to select terms which registered or taught by user (e.g.student & faculty).

The ideal change on Dialog window is show the correct start date and end date of quad class as it should.
The second solution is adding a quad session (e.g. Q3, Q4) in the column Term date, without need to change the start and end date.

**Comment by mla04762** [comment]
We are improving this feature by creating a new query so that we can get one full schedule from the api instead of sending numerous requests.

**Comment by russtuck** [comment]
This looks done to me.  Closing.
