### ISSUE TITLE
Appearance Settings bug/visual fixes

### ISSUE THREAD

**Issue by amos-cha** [gordon-cs/gordon-360-ui#2221]
![Image](https://github.com/gordon-cs/gordon-360-ui/assets/78386128/68a7443c-b3ab-414c-8b59-14081db74334)

-Switching between System Default (if Dark) and Dark flashes text as white for whatever reason.
- [ ] Color mode text does not look good. 
- [ ] Disable option that is not System Default? i.e. If my system default is Dark, do not let me choose dark.

**Comment by russtuck** [comment]
Pushed
