### ISSUE TITLE
Rec-IM Create Team post end of Registration/Beginning of Activity

### ISSUE THREAD

**Issue by amos-cha** [gordon-cs/gordon-360-ui#2254]
![image](https://github.com/gordon-cs/gordon-360-ui/assets/78386128/03a83600-243a-4b61-bf39-97648d2ab16b)
Don't let teams be made post end of registration/beginning of activity

**Comment by bennettforkner** [comment]
Are you adding a description to this @amos-cha ? This picture and the title of the issue do not speak for themselves to someone without your context.

**Comment by amos-cha** [comment]
> Are you adding a description to this @amos-cha ? This picture and the title of the issue do not speak for themselves to someone without your context.

![image](https://github.com/gordon-cs/gordon-360-ui/assets/78386128/666eaca0-e21b-45ed-a661-e9e10fe2d859)
