### ISSUE TITLE
Add iAttended to Links page

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#2265]
Since we have removed Chapel Credits from the homepage dashboard, it would be good to have a link to iAttended. The webpage is [iAttendedApp.com](https://iattendedapp.com/). That page has a link to the app store and google play store for people who don't have the app to get it. Users can also sign in to the website and access most or all of iAttended's features that way.

**Comment by SeanAverS** [comment]
Hello, 

I am interested in working on this issue. Could I please be assigned to it? Thanks.

**Comment by SeanAverS** [comment]
Hello,

I am interested in working on this issue. Could I please be assigned? Thanks.
