### ISSUE TITLE
back-to-back quad courses wrap in course schedule

### ISSUE THREAD

**Issue by jsenning** [gordon-cs/gordon-360-ui#2287]
There are some formatting issues when two back-to-back quad courses appear in the same timeslot on the schedule; here is an example:

![Image](https://github.com/gordon-cs/gordon-360-ui/assets/6454529/f1b902d8-384e-4664-8a6e-a578148cee10)

Maybe we need to change the font size?  Also, while we're looking at this, is there some way to better distinguish the course code from the building/room number?

**Comment by Hls5235** [comment]
I actually just started working on this, however I believe the course code and room number issue that your talking about actually won’t be a problem once this is fixed and correct me if I’m wrong, MAT 227 is the title and KOSC is the building but the room code actually isn’t on the screen and that’s why it’s hard to distinct the two.

**Comment by jsenning** [comment]
MAT 227 should be in the same room as MAT 226.  I think the program displays "MAT 227" but it wraps so  that when it tries to display "KOS 126" we get just the "KOS" but "126" would be below that if the schedule card was larger.  You could maybe test this by changing the hours we show courses for (i.e. start at 12:00pm rather than 8:00am).

Just a thought, but we often write course codes without a space, so maybe using "MAT226" and "MAT227" would help.  Maybe also reducing the font size would help.

That said, The problem could be worse - if the course has a section code or lab code.   The example that comes to mind is BUS105FA and BUS105FB (look at Kent Siebert's fall teaching schedule).
