### ISSUE TITLE
Events Page Showing No Events

### ISSUE THREAD

**Issue by Centerville1** [gordon-cs/gordon-360-ui#2380]
Events view on public 360 not showing events.  Currently it just shows the loader for a few seconds then says no events to show.  I think I noticed this on train the other day too, possibly this is related to the recent changes in #2377?  The response from the API to the events GET request appears to be an empty array when viewing the network traffic, but I could be misreading that.

![Image](https://github.com/user-attachments/assets/e6f00e80-9a5a-4cd6-ab49-691544732117)

**Comment by EjPlatzer** [comment]
It appears that this was a transient error. When I checked last night and this morning, the events page is loading events as expected. I suspect it may have been an issue with the 25Live API.
