### ISSUE TITLE
Preserving Search Through Back-Button

### ISSUE THREAD

**Issue by softwary** [gordon-cs/gordon-360-ui#340]
"It's nice to have a working back-button!" (- Natou) but it's annoying for our search parameters to disappear after you click it.

We can possibly fix this with a variable that's passed between the pages that saves your search params.

**Comment by EjPlatzer** [comment]
This issue is outdated. This feature has been mostly implemented by writing searches as history with parameters encoded in the url query string. People Search and Involvements search still leave some to be desired in this respect, but there are clearer and more focused issues addressing those.
