### ISSUE TITLE
Super Admin Page - confirming final rosters and adding other super admins

### ISSUE THREAD

**Issue by chris-hansen** [gordon-cs/gordon-360-ui#346]
- [ ] Be able to Close (Confirm)/Re-open Roster for all involvements
- [ ] Be able to assign or remove other Super-Admins
- [ ] Admin page should be accessible from Navatar Menu, with above functionality

**Comment by ChrisImagineer** [comment]
Once the Spring session closed, there is no SuperAdmin view to manage the open and closed groups for that session. 
[ ] Add a "session" selector, and allow view of open-closed status for any session?
[ ] How to view sessions needing managment once the session date turns over?
