### ISSUE TITLE
Add Member name field "requires" full email address?

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#352]
The add member name field seems to want only firstname.lastname@gordon.edu full address, but there is no warning that an incomplete string or a wrong name is not accepted. If you type only the Exchange first.last-only, when you click Add Member, just nothing happens?

- [x] Can the acceptable name string be a valid Exchange first.last or the full email? (shorter one preferred!)
- [ ] Can a user error note appear to instruct that a name was not accepted, check the name and try again or whatever?
- [ ] long-term - autocomplete valid Exchange names/emails!

These affect GroupAdmins the most because they are entering 5-50 names at a time, and it can be very frustrating not to see what you did incorrectly.

Current work around for GroupAdmins is using 360old to enter group names for the roster.

[Edited to make list into task-list with checkboxes]

**Comment by jason-whitehouse** [comment]
This appears to be working with just AD username in production.
