### ISSUE TITLE
Clicking "Add member" without selecting a participtation causes backend to crash

### ISSUE THREAD

**Issue by NathanielRudenberg** [gordon-cs/gordon-360-ui#374]
If you try to add a member without selecting a participation from the dropdown menu, it appears to do nothing (but the backend throws an exception). Ideally, either an error message should be displayed in the dialog box or the button should be disabled until a participation is selected.

**Comment by jason-whitehouse** [comment]
This is working in production.  An error message prompts selection of participation level.
