### ISSUE TITLE
Update Meal Plan

### ISSUE THREAD

**Issue by softwary** [gordon-cs/gordon-360-ui#388]
This is for the use case of changing meal plans, which happens every semester. It makes sense to have a place to change your plan on the site where you see how many meal points you have.

There are 5 meal plan options M1, M2 & (apartment dwellers) A1, A2, A3

You enter your ID, your housing, and your meal plan preference.

**Comment by bennettforkner** [comment]
This would actually not be a difficult thing to move over as far as the back-end processing logic goes. All it is is a freeform on the GO site. If we were to move it into 360, we would need to drop responses back into the freeform database tables to be processed.

**Comment by antoniavonto** [comment]
https://github.com/gordon-cs/gordon-360-ui/pull/2046
