### ISSUE TITLE
Cropper does not handle vertical photos well on mobile.

### ISSUE THREAD

**Issue by isaacbleecker** [gordon-cs/gordon-360-ui#438]
Especially when you take the picture in the cropper interface vertically, it will assume the picture is horizontal and chop off the top and bottom. Worth fixing.

**Comment by dli505** [comment]
I think this is fixed? It looks fine to me on both mobile and web for vertical and horizontal photos respectively.

**Comment by Luke-W-Hart** [comment]
The current cropper fixes this bug.
