### ISSUE TITLE
Implement Add to Calendar buttons for events

### ISSUE THREAD

**Issue by joshuaRogers24** [gordon-cs/gordon-360-ui#546]

**Comment by andrew-wzj** [comment]
I am interested in adding calendar button for event, and I wonder to discuss the design in detail. Also question for how to access user's calendar.

**Comment by andrew-wzj** [comment]
https://github.com/gordon-cs/gordon-360-ui/pull/1822
This is the linked pull requests

**Comment by mla04762** [comment]
@bennettforkner We weren't able to find a way to get two separate time's for the start and end time for a event (we could only get one string that combined the two times as a range), is there a way to get this from the api?

**Comment by bennettforkner** [comment]
> @bennettforkner We weren't able to find a way to get two separate time's for the start and end time for a event (we could only get one string that combined the two times as a range), is there a way to get this from the api?

https://github.com/gordon-cs/gordon-360-ui/blob/develop/src/services/event.ts

The event service shows the structure of our event objects in typescript. There is a start and end date (and time). I'm not 100% sure where you are getting events without separate dates.

**Comment by mla04762** [comment]
We didn't see that until now, we will look into that. Thank You!

**Comment by bennettforkner** [comment]
I recommend tracing back the calls from EventItem backwards so that you can find exactly what type is being passed to it.
