### ISSUE TITLE
Guest View is Incomplete

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#580]
The site now allows unauthenticated (Guest) users to access a limited view of 360. This view is an excellent marketing and recruitment tool. However, there is still lots of polishing left to do. The most important improvements are:
- [x] Add a welcome message to the homepage informing guests of what they're seeing. this message would appear above/alongside the login box and would help non-Gordon users to understand our site and what they do have access to.
- [x]  Migrate Login to a dialog that can be accessed from anywhere and leaves you on the page you were already on before logging in. Currently, the Login component is in the unauthenticated view of the Home page, and clicking sign in from any menu simply navigates the user to this home page. However, this means that a user has to leave the page they're on, sign in, and then navigate back to that page in order to see the authenticated version of it. Instead, the Login should be put in a Dialog Box (probably in the NavAvatarRightCorner and NavLinks components) that opens whenever the user clicks a sign in button. Logging in from this dialog box should update the authentication and re-render whatever page the user was already on.
- [x] Finally, Chris Carlson has requested that guests be given access to a sample Experience Transcript (which would staticly display some mocked up data and explain the purpose and meaning of the Transcript). This Transcript wouldn't be accessible via myProfile, since guests do not have a profile, so it would have to be given a different access point, either a Tab in the header or a link in the Nav Menus. See #1808

**Comment by EjPlatzer** [comment]
Of the above steps:
1. is a good first issue
2. requires more familiarity with the codebase but would be a good code quality upgrade
3. Requires a new element be added to the UI and designed in cooperation with Chris Carlson. It would probably have to come after a more thorough update of the Experience Transcript UI and might require additions to the database as well.

**Comment by ArabellaJi** [comment]
I'm working on creating the transcript for the guest now and created an issue for it. See more details here: #1808.
