### ISSUE TITLE
Fix the issue where clicking on another profile brings you to your own profile (2)

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#63]

**Comment by NathanielRudenberg** [comment]
Changing the URL to ```[server address]:[port]/profile/[literally anything]``` (where ```[server address]``` is replaced with your local server address, ```[port]``` is replaced with your port number, and ```[literally anything]``` is replaced with literally anything) will also load the profile of the current user.

**Comment by jsenning** [comment]
Yes - that's the behavior I've been seeing.  I've found a branch
    that seems to fix this and am working this afternoon to turn it into
    something we can merge with "develop".
    
    On 06/15/2018 02:28 PM,
      NathanielRudenberg wrote:
    
    
      
      Changing the URL to [server
          address]:[port]/profile/[literally anything] (where [server
          address] is replaced with your local server address, [port]
        is replaced with your port number, and [literally
          anything] is replaced with literally anything) will
        also load the profile of the current user.
      —
        You are receiving this because you were assigned.
        Reply to this email directly, view it on GitHub, or mute the thread.
      {"@context":"http://schema.org","@type":"EmailMessage","potentialAction":{"@type":"ViewAction","target":"https://github.com/gordon-cs/gordon-360-ui/issues/63#issuecomment-397705773","url":"https://github.com/gordon-cs/gordon-360-ui/issues/63#issuecomment-397705773","name":"View Issue"},"description":"View this Issue on GitHub","publisher":{"@type":"Organization","name":"GitHub","url":"https://github.com"}}
      {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/gordon-cs/gordon-360-ui","title":"gordon-cs/gordon-360-ui","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/gordon-cs/gordon-360-ui"}},"updates":{"snippets":[{"icon":"PERSON","message":"@NathanielRudenberg in #63: Changing the URL to ```[server address]:[port]/profile/[literally anything]``` (where ```[server address]``` is replaced with your local server address, ```[port]``` is replaced with your port number, and ```[literally anything]``` is replaced with literally anything) will also load the profile of the current user."}],"action":{"name":"View Issue","url":"https://github.com/gordon-cs/gordon-360-ui/issues/63#issuecomment-397705773"}}}
      {
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [gordon-cs/gordon-360-ui] Fix the issue where clicking on another profile brings you to your own profile (TBD) (#63)",
"sections": [
{
"text": "",
"activityTitle": "**NathanielRudenberg**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@NathanielRudenberg",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"gordon-cs/gordon-360-ui\",\n\"issueId\": 63,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"gordon-cs/gordon-360-ui\",\n\"issueId\": 63\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/gordon-cs/gordon-360-ui/issues/63#issuecomment-397705773"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 345697242\n}"
}
],
"themeColor": "26292E"
}
    
    
    -- 
      Jonathan R. Senning
      Professor of Mathematics and Computer Science
      Gordon College, 255 Grapevine Road, Wenham MA 01984-1899
      Voice: 978-867-4376, FAX: 978-867-4585
      Email: Jonathan.Senning@gordon.edu
      Web: http://www.math-cs.gordon.edu/~senning
