### ISSUE TITLE
investigate odd URL sent to API server

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#631]
Chris Hansen wrote (in email):
I just noticed this is the event viewer, which  might be a mistake in the code somewhere that’s rendering this odd path:
![image001](https://user-images.githubusercontent.com/12618649/63725717-2ca90700-c829-11e9-99e8-f2e4f115e9a8.png)

Me: I wonder if it's related to fixing the back button -- either it's odd looking but correct, or perhaps an unexpected result of guest view and the back button code.

**Comment by EjPlatzer** [comment]
This URL is (perhaps odd-looking but) correct. The AccountsController in the API uses the route `api/advanced-people-search/{includeAlumniSearchParam}/{firstNameSearchParam}/{lastNameSearchParam}/{majorSearchParam}/{minorSearchParam}/{hallSearchParam}/{classTypeSearchParam}/{hometownSearchParam}/{stateSearchParam}/{countrySearchParam}/{departmentSearchParam}/{buildingSearchParam}`. As you can see, the first two parameters are includeAlumni and firstName. So it looks the Front End or (as I suspect) a service like Postman sent a request to the API for a search that shouldn't include alumni and should search for the first name Ester.

Oddly, the API expects the string `C#` in place of an empty string for parameters that shouldn't be used to search. Perhaps there were difficulties sending null strings. It might've been better, in hindsight, to use URL query parameters, e.g. `api/advanced-people-search?firstname=ester...` instead, but it would be a lot of work for little gain to change this now.

The issue with that request is that whoever was sending it wasn't authenticated. It might've been a bug with the UI that allowed someone to submit a search without logging in. More likely, in my opinion, was that someone was sending requests to the API manually using a service like Postman and didn't authenticate their request.

Either way, this is the expected and correct behavior for the API, so I'm going to close this issue.
