### ISSUE TITLE
FacStaff personal info is missing

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#644]
Information that faculty and staff have chosen to make available to the college community is not being shown in 360 people search results.  (It's still in go.gordon.edu.)

This makes 360 less useful, and prevents replacing this feature of go.  (There should be just one directory system to maintain.  Otherwise, we'll waste time maintaining 2, and they'll never be the same.)

I chose to make my spouse's name and my home address  visible.  And now they are not.

**Comment by bennettforkner** [comment]
They are visible at this point.
