### ISSUE TITLE
Unable to leave an involvement you are a member of.

### ISSUE THREAD

**Issue by babbett** [gordon-cs/gordon-360-ui#652]
Clicking the 'Leave' button on the involvement profile page results in a confirmation popup. Hitting 'Yes, leave' has no effect. (However, the cancel button works correctly).

Maybe part of the unused API routes?

Error thrown: asyncToGenerator.js:6 Uncaught (in promise) w {name: "NotFoundError", message: "Resource not found"}message: "Resource not found"name: "NotFoundError"__proto__: Error__proto__: Object

**Comment by NathanielRudenberg** [comment]
After the API fix is merged, we should also maybe add action feedback to the front end so that if something does go wrong, the user is aware. Maybe through error text or a snackbar?
