### ISSUE TITLE
No one can remove people from an involvement unless they are a super-admin

### ISSUE THREAD

**Issue by jason-whitehouse** [gordon-cs/gordon-360-ui#657]
UPDATE: This may have been fixed by ajabbot and/or NathanielRudenberg. You can leave an involvement yourself (whether past or current). You can also subscribe and unsubscribe, although, the benefits of subscription were not tested. The ability for group admins to remove people was also not tested.

Students who are group admins for an activity cannot remove members.  They are able to click remove successfully, but the OK button is not responsive on the confirm popup.  The cancel button works just fine, but the OK button does not.  Site Admins CAN remove people (ie the OK button on remove works.)  

I am unsure at this time if fac/staff group admins who are not site admins have the same problem.

Edit: Another issue claimed that "Join" appears to be successful but is not.

Edit  (copied from another similar issue): Maybe this is a result of the so-called "unused" API routes being removed?

Edit (copied from another similar issue): Error thrown: asyncToGenerator.js:6 Uncaught (in promise) w {name: "NotFoundError", message: "Resource not found"}message: "Resource not found"name: "NotFoundError"proto: Error__proto__: Object

**Comment by jason-whitehouse** [comment]
It seems no one is able to remove members from a group unless they are a super-admin based on my testing in 360train

**Comment by EjPlatzer** [comment]
This issue appears to have been fixed. Students who are group admins can successfully add and remove people, and FacStaff who are group admins can also add and remove people. The join button works correctly. All testing was done with accounts that were not site administrators.
