### ISSUE TITLE
Schedule is for last term, when new term is about to start.

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#664]
It's almost time for the Spring Semester, so I'm updating my schedule with my new office hours.  But it still shows last fall's classes.  Spring classes would be much more useful!

It would also be more useful to see other people's coming class schedules, not their old ones.

Maybe switch over at the halfway point between terms?  Switch from fall to spring on Jan 1?

**Comment by bennettforkner** [comment]
This is an older copy of issue #1326
