### ISSUE TITLE
Manually entering profile URL gives a 404 (7)

### ISSUE THREAD

**Issue by NathanielRudenberg** [gordon-cs/gordon-360-ui#68]
If you click on the profile button in the navbar, the website loads and serves your profile page. Pasting the exact same URL currently gives 404.

**Comment by scmac97** [comment]
Actually, it looks like manually entering **any** URL &mdash; or refreshing any page &mdash; yields a 404 error. This only occurs when the website is live, and not when it is being run locally with `npm`.

**Comment by scmac97** [comment]
Might this have something to do with React Router?

**Comment by scmac97** [comment]
**Idea** &mdash; this might be what is happening: React Router handles links on click, but if you type in a URL, it gets sent to the server before it can be handled by React Router

**Comment by NathanielRudenberg** [comment]
Closing because there is now a pull request that fixes this problem.
