### ISSUE TITLE
Schedule feature for Students and Faculty only.

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#687]
Make the Schedule viewable for a Student Profile. Consider making it viewable for Faculty, but optional to display for Staff/Administration. Make it not viewable on an Alumni profile.

**Comment by andrew-wzj** [comment]
The only problem for this issue is the schedule of Alumni is viewable in its public profile.

**Comment by andrew-wzj** [comment]
When student is label as Alumni instead of Student type, the database migrates these data to other place.

**Comment by Hls5235** [comment]
This has been resolved.  #2323
