### ISSUE TITLE
What info should be shown on MyProfile and PublicProfile?

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#732]
~~1 ) Add to the Social Media links, a spot for user's Handshake link~~

~~2 ) Consider changing Profile involvements to show only Current ones or public view, with toggles to turn off ones that someone wants to leave off (the list can look really long).~~

~~2a ) But, Show All Involvements on Experience Transcript, even if the person toggles off in their Public View.~~

3 ) Discuss what other info should and should not be on the Profile (imagination step, not an action step)

**Comment by EjPlatzer** [comment]
The handshake part of this has been implemented and released by #854.

**Comment by josh-peters-2357** [comment]
@ChrisImagineer Chris, could you expand a little on what you mean by "Change Profile involvements to show only Current for public view, with toggles. Show other/all Involvements on Experience Transcript."? I am working on this issue and have made some progress, but want to make sure I know what you intended.

**Comment by EjPlatzer** [comment]
2 and 2a are superseded by #742.

**Comment by EjPlatzer** [comment]
Closing after discussion with Chris
