### ISSUE TITLE
Image field for Group Pages

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#734]
Add image to the group roster and group leaders

**Comment by roddy3** [comment]
@Davideo37, here is the project.

**Comment by roddy3** [comment]
Pictures of the Leaders/Advisor of the group next to their names, see an example below  



![Screen Shot 2021-06-09 at 1 23 02 PM](https://user-images.githubusercontent.com/60272749/121400744-efdad100-c925-11eb-81c3-03079869a54d.png)



Have a place where they can share their past important events, and also their about/origins pretty much similar to what 360 has see example below



![Screen Shot 2021-06-09 at 1 29 49 PM](https://user-images.githubusercontent.com/60272749/121401608-e43bda00-c926-11eb-8240-d3c174a83dd5.png)

**Comment by Davideo37** [comment]
After hearing feedback from a couple of the club leaders, we also discovered a couple UI

> 
> 
> Pictures of the Leaders/Advisor of the group next to their names, see an example below
> 
> ![Screen Shot 2021-06-09 at 1 23 02 PM](https://user-images.githubusercontent.com/60272749/121400744-efdad100-c925-11eb-81c3-03079869a54d.png)
> 
I made a separate issue for this #1182

**Comment by roddy3** [comment]
Thanks you @Davideo37

**Comment by roddy3** [comment]
Duplicate of #1182
