### ISSUE TITLE
(1) Change My Profile link in offline mode to the regular My Profile page and not the user's public profile

### ISSUE THREAD

**Issue by jahnueldorelus** [gordon-cs/gordon-360-ui#833]

**Comment by bennettforkner** [comment]
I don't think this is actually a good idea. MyProfile provides a bunch of functionality that would not work if the user were offline. You would have to do a lot more work to build a third "offline myprofile" version of the component. That would likely not be worth the work for the amount of use that the PWA gets offline. Therefore, we should probably leave it as the public profile.
