### ISSUE TITLE
Add Member confirmation incomplete

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#870]
Add member confirmation does not clear, and the membership dialog box remains with that member's information on the screen. Should the X closing the confirmation (or a timeout) also close the dialog box or wipe the dialog box? Or is there intention to leaving the dialog box with the previously-entered data?

**Comment by jason-whitehouse** [comment]
CTS Request 131197 (internal to CTS) Updated description:

Bug - (startup issue for group leaders) – Adding a group member to a roster (first.last + role + title), on SUBMIT, a “Success!” dialog box appears, but does not self-close or process the page. You can close the "Success!" dialog, but then the page does not refresh. The member entry box remains with that previous data. The only options are Submit (again) or “Cancel” – yet Cancel implies you haven’t added.  If you do Cancel, and then manually refresh the page, the roster add is recorded, so submissions are being added, but the user will not know this.
