### ISSUE TITLE
term days makes no sense

### ISSUE THREAD

**Issue by russtuck** [gordon-cs/gordon-360-ui#883]
Today, 9/23/20, I see 59 days finished and 86 days left.  Neither makes sense.

Classes started on 8/20, 36 days ago (not counting today, since it's not finished).
Classes will end on 12/4, 73 days from now (including today).  Even if there's an invisible "finals" time included (since we normally would have that), it wouldn't add 13 days.

This might be a backend or database issue (I haven't investigated), but it's at least a visible issue.

**Comment by EjPlatzer** [comment]
I don't think this is a bug, I think it's an artifact of Gordon's internal term tracking. The start and end dates are not especially relevant to the student's academic schedule unfortunately. 

See #353 for reference. I am going to close this issue and leave that question open.
