### ISSUE TITLE
Academic Checkin

### ISSUE THREAD

**Issue by ChrisImagineer** [gordon-cs/gordon-360-ui#885]
Move Academic/Enrollment Check in to 360

**Comment by Davideo37** [comment]
Do we have access to the current code for the academic check in on the go site? It would help as a starting point to figure out what needs to be added to 360.

**Comment by ChrisImagineer** [comment]
This would be a check-with-Evan. That current process is championed by Dan Savlon, System Developer, CTS/Registrar’s office

On 06/03/21, 11:19, "Davideo37" ***@***.******@***.***>> wrote:


Do we have access to the current code for the academic check in on the go site? It would help as a starting point to figure out what needs to be added to 360.

**Comment by Davideo37** [comment]
Me and Silas have essentially finished the Front-End UI and are working on the Back-End with the assistance of Evan. Here are some screenshots of the current pages for each step of the check-in, as well as a "Confirm" page we added that was not present in the original Go site check in. @ChrisImagineer let us know if you have any comments or suggestions for the visual UI part, and we can address those before we finalize the design once the Back-End is working.

(Note: a few of these pages were too large to fit in a single screenshot so I tried to stitch together pieces to show the full page in one picture.)

Main Check In:
![ui1](https://user-images.githubusercontent.com/70544021/122596460-e80ee100-d037-11eb-8711-f241b714c305.PNG)
Page 1 Emergency Contact:
![ui2_1](https://user-images.githubusercontent.com/70544021/122596487-f230df80-d037-11eb-890d-be89307d9355.PNG)
Page 2 Personal Cell Phone:
![ui3](https://user-images.githubusercontent.com/70544021/122597147-f90c2200-d038-11eb-8b83-9389fe07f794.PNG)
Page 3 Privacy Agreements:
![ui4_1](https://user-images.githubusercontent.com/70544021/122597158-fb6e7c00-d038-11eb-8ceb-9b520a43e348.PNG)
Page 4 Race/Ethnicity:
![ui5](https://user-images.githubusercontent.com/70544021/122597175-032e2080-d039-11eb-8ad3-0481c3afb2d9.PNG)
Page 6 Confirm Information
![ui6](https://user-images.githubusercontent.com/70544021/122597195-0cb78880-d039-11eb-95e1-0e121ab1fe8b.PNG)

**Comment by ChrisImagineer** [comment]
Hi, Can you also share these developments with Dan Savlon in the Registrar’s office, too. Moving the checkin from go.gordon to 360 has been a goal for a while and Dan is the link for us.
  These screenshots look great, thanks for gathering all the text from these screens. Most student users will complete this step on mobile, so just double-check the views on sample devices/platforms.

On 06/18/21, 13:31, "David Gurge" ***@***.******@***.***>> wrote:

Me and Silas have essentially finished the Front-End UI and are working on the Back-End with the assistance of Evan. Here are some screenshots of the current pages for each step of the check-in, as well as a "Confirm" page we added that was not present in the original Go site check in. @ChrisImagineer<https://github.com/ChrisImagineer> let us know if you have any comments or suggestions for the visual UI part, and we can address those before we finalize the design once the Back-End is working.

(Note: a few of these pages were too large to fit in a single screenshot so I tried to stitch together pieces to show the full page in one picture.)

Main Check In:
[ui1]<https://user-images.githubusercontent.com/70544021/122596460-e80ee100-d037-11eb-8711-f241b714c305.PNG>
Page 1 Emergency Contact:
[ui2_1]<https://user-images.githubusercontent.com/70544021/122596487-f230df80-d037-11eb-890d-be89307d9355.PNG>
Page 2 Personal Cell Phone:
[ui3]<https://user-images.githubusercontent.com/70544021/122597147-f90c2200-d038-11eb-8b83-9389fe07f794.PNG>
Page 3 Privacy Agreements:
[ui4_1]<https://user-images.githubusercontent.com/70544021/122597158-fb6e7c00-d038-11eb-8ceb-9b520a43e348.PNG>
Page 4 Race/Ethnicity:
[ui5]<https://user-images.githubusercontent.com/70544021/122597175-032e2080-d039-11eb-8ad3-0481c3afb2d9.PNG>
Page 6 Confirm Information
[ui6]<https://user-images.githubusercontent.com/70544021/122597195-0cb78880-d039-11eb-95e1-0e121ab1fe8b.PNG>
