### ISSUE TITLE
CL&W events are not showing up in 360

### ISSUE THREAD

**Issue by joshuaRogers24** [gordon-cs/gordon-360-ui#887]
This seems to be connected to chapel being held outside since it only started happening with this change. 

![noCL W](https://user-images.githubusercontent.com/47014800/95662909-6d84dd80-0b08-11eb-81fe-266961f04eb0.png)

![noCL W2](https://user-images.githubusercontent.com/47014800/95662912-6f4ea100-0b08-11eb-9124-38b7e480356f.png)

**Comment by EjPlatzer** [comment]
Duplicate issue of #882
