### ISSUE TITLE
Make it so the student landing page disables the create application button (and explains) if the user already has a saved application for the current session

### ISSUE THREAD

**Issue by joshuaRogers24** [gordon-cs/gordon-360-ui#932]

**Comment by NerdyGriffin** [comment]
Requires the completion of https://github.com/gordon-cs/gordon-360-api/issues/422

**Comment by NerdyGriffin** [comment]
Suggested alternative:

Make it so the student landing page shows the date/time it was last modified and a "view application" button (and explains) if the user already has a saved application for the current session
