### ISSUE TITLE
Involvements membership requests text is outside it's card / Involvement Grid Cutoff 

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#961]
When viewing membership requests on the involvements page (must be a group admin to do so), the text for received requests floats outside of it's card in an ugly way.
![image](https://user-images.githubusercontent.com/35319956/106303675-66551d00-6228-11eb-8be7-05708f40822f.png)

**Comment by speroJay** [comment]
Unsure if these grids can be fixed or not (due to general sizing) - but it looks rather poor on small devices
![image](https://user-images.githubusercontent.com/78441402/108892131-8684bb80-75dd-11eb-8bd1-f5cfa08f3849.png)
