### ISSUE TITLE
Refactor deprecated method `componentWillMount`

### ISSUE THREAD

**Issue by EjPlatzer** [gordon-cs/gordon-360-ui#962]
The React component method `componentWillMount` has been deprecated. In a class component, it should be replaced with `componentDidMount`, which is virtually identical.

Thanks to a generous contribution from the GitHub community, [branch removeWillMount](https://github.com/gordon-cs/gordon-360-ui/tree/removeWillMount) has the first step of this process complete. The next step is to clean up components with duplicate calls of componentDidMount, and then testing a local run to ensure the updated components function correctly.

**Comment by dezy-x2** [comment]
Hi, I would like to take this on. Just to clarify I just need to swap out `componentWillMount()` with `componentDidMount` correct? Thank you

**Comment by josh-peters-2357** [comment]
@dezy-x2 @EjPlatzer Maybe we could link #964 to this issue so it can be closed?

**Comment by EjPlatzer** [comment]
That was a good start to the issue, but as  you can see from the issue description, there is still more to be done. At this point, there's some cleanup that needs to be done and then a lot of testing the system to ensure the changes haven't broken anything.
